import { test, expect } from '@playwright/test';
import { mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import type { Workspace, Plan } from '../apps/shared/types.ts';

test('product demo: run → human edit → review → stale rejection → conditional commit → reload', async ({ page, request }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  const shots = resolve('docs/screenshots'); mkdirSync(shots, { recursive: true });
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Your asset workspace.' })).toBeVisible();
  await expect(page.locator('.asset-card')).toHaveCount(3);
  await page.screenshot({ path: `${shots}/01-workspace.png`, fullPage: true });
  await page.getByRole('link', { name: 'New agent run', exact: true }).click();
  await expect(page.getByLabel('YOUR TASK')).toHaveValue('Prepare approved assets for Autumn Launch');
  await expect(page.getByRole('button', { name: /Live model/ })).toBeDisabled();
  await page.getByRole('button', { name: 'Run task', exact: true }).click();
  await expect(page.getByText('Run finished. Your changes are ready to inspect.')).toBeVisible();
  await expect(page.locator('.timeline code')).toHaveText(['assets_list', 'asset_get', 'asset_get', 'asset_patch', 'asset_patch']);
  await expect(page.getByLabel('Agent workflow')).toContainText('4 persisted Effects');
  await page.screenshot({ path: `${shots}/02-agent-run.png`, fullPage: true });
  await page.getByRole('link', { name: 'View workspace', exact: true }).click();
  await page.getByRole('button', { name: 'Edit asset_b', exact: true }).click();
  await page.getByRole('dialog').getByLabel('Display name').fill('Hero — Final');
  await page.getByRole('button', { name: 'Save human edit', exact: true }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await expect(page.getByRole('heading', { name: 'Hero — Final', exact: true })).toBeVisible();
  await page.getByRole('link', { name: /Update asset_b/ }).click();
  await expect(page.getByRole('row', { name: /display_name/ }).getByText('Protected', { exact: true })).toBeVisible();
  await expect(page.getByRole('row', { name: /campaign/ }).getByText('Eligible', { exact: true })).toBeVisible();
  await expect(page.locator('.protection-card').getByText('A newer human edit owns this field', { exact: true })).toBeVisible();
  await page.screenshot({ path: `${shots}/03-action-detail.png`, fullPage: true });
  await page.getByRole('link', { name: 'Review undo', exact: true }).click();
  await expect(page.getByLabel('Change summary')).toContainText('Agent changed 2 fields.');
  await expect(page.getByLabel('Change summary')).toContainText('1protected human edit');
  await expect(page.locator('.protection-explanation')).toHaveText('Human changed this field after the agent action.');
  await page.getByRole('button', { name: 'Preview Undo', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Commit Undo', exact: true })).toBeEnabled();
  await page.screenshot({ path: `${shots}/04-undo-review.png`, fullPage: true });
  const before = await (await request.get('/api/workspace')).json() as Workspace;
  const assetC = before.assets.find(a => a.resourceId === 'asset_c')!;
  const edited = await request.post('/api/human-edits', { data: { resource_id: 'asset_c', operation_key: 'test-later-note',
    writes: [{ field: 'note', value: 'A later human note', expected_revision: assetC.fields.note.revision }] } });
  expect(edited.ok()).toBe(true);
  await page.getByRole('button', { name: 'Commit Undo', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Your workspace changed after this preview');
  const unchanged = await (await request.get('/api/workspace')).json() as Workspace;
  expect(unchanged.assets.find(a => a.resourceId === 'asset_b')!.fields.campaign.value).toBe('Autumn Launch');
  await page.screenshot({ path: `${shots}/06-stale-plan.png`, fullPage: true });
  await page.getByRole('button', { name: 'Preview Undo', exact: true }).click();
  await page.getByRole('button', { name: 'Commit Undo', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Protected changes preserved.', exact: true })).toBeVisible();
  await expect(page.getByText('Already undone', { exact: true })).toBeVisible();
  await page.screenshot({ path: `${shots}/05-undo-completed.png`, fullPage: true });
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Protected changes preserved.', exact: true })).toBeVisible();
  const after = await (await request.get('/api/workspace')).json() as Workspace;
  const b = after.assets.find(a => a.resourceId === 'asset_b')!;
  expect(b.fields.campaign).toMatchObject({ value: null, revision: 2, activeEffectId: null });
  expect(b.fields.display_name.value).toBe('Hero — Final');
  expect(after.assets.find(a => a.resourceId === 'asset_c')!.fields.note.value).toBe('A later human note');
  expect(after.actions).toHaveLength(2);
  const committed = after.actions.find(a => a.effects[0].resourceId === 'asset_b')!.receipt!;
  const retry = await request.post('/api/undo/commit', { data: { undo_plan_id: committed.undo_plan_id } });
  expect(await retry.json()).toEqual(committed);
  // The rest of this Run is a separate Action, not one atomic batch undo.
  const actionA = after.actions.find(a => a.effects[0].resourceId === 'asset_a')!;
  const planA = await (await request.post('/api/undo/preview', { data: { action_id: actionA.action.id } })).json() as Plan;
  expect(planA).toMatchObject({ eligible: 2, protected: 0 });
  expect((await request.post('/api/undo/commit', { data: { undo_plan_id: planA.undo_plan_id } })).ok()).toBe(true);
  const finalWorkspace = await (await request.get('/api/workspace')).json() as Workspace;
  const a = finalWorkspace.assets.find(a => a.resourceId === 'asset_a')!;
  expect(a.fields.display_name.value).toBe('Cake 01');
  expect(a.fields.campaign).toMatchObject({ value: null, revision: 2 });
  expect(finalWorkspace.assets.find(a => a.resourceId === 'asset_b')!.fields.display_name.value).toBe('Hero — Final');
  // A narrow screen keeps the main workflow usable and horizontally contained.
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/#/workspace');
  await expect(page.getByRole('heading', { name: 'Hero — Final' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: `${shots}/07-mobile.png`, fullPage: true });
  const clearStatus = await request.post('/api/human-edits', { data: { resource_id: 'asset_c', operation_key: 'test-null-status',
    writes: [{ field: 'status', value: null, expected_revision: assetC.fields.status.revision }] } });
  expect(clearStatus.ok()).toBe(true);
  await page.reload();
  await page.getByRole('button', { name: 'Edit asset_c', exact: true }).click();
  await page.getByRole('dialog').getByLabel('Note').fill('Only the note changes');
  await page.getByRole('button', { name: 'Save human edit', exact: true }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  const nullStatus = await (await request.get('/api/workspace')).json() as Workspace;
  expect(nullStatus.assets.find(a => a.resourceId === 'asset_c')!.fields.status.value).toBeNull();
  expect(errors).toEqual([]);
});
